{
 "title": "Greengrass Telemetry Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT DISTINCT thing_name from telemetry;"
   }
  ]
 },
 "panels": [
  { "title": "At a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  ts / 1000 as time,\n  n,\n  thing_name,\n  v::float4\nFROM\n  telemetry\nWHERE\n  n='CpuUsage'\nAND\n  ts / 1000 >= $__unixEpochFrom() AND ts / 1000 <= $__unixEpochTo() \nORDER BY time ASC;"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  ts / 1000 as time,\n  thing_name,\n  v::float4\nFROM\n  telemetry\nWHERE\n  n='SystemMemUsage'\nAND\n  ts / 1000 >= $__unixEpochFrom() AND ts / 1000 <= $__unixEpochTo() \nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Total File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "rawSql": "SELECT\n  ts / 1000 as time,\n  n,\n  thing_name,\n  v::float4\nFROM\n  telemetry\nWHERE\n  n='TotalNumberOfFDs'\nAND\n  ts / 1000 >= $__unixEpochFrom() AND ts / 1000 <= $__unixEpochTo() \nORDER BY time ASC;\n"
    }
   ]
  },
  {
   "title": "Component Status (${device})",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  ts / 1000 as time,\n  n as metric,\n  CASE v\n    WHEN 'RUNNING' THEN 0\n    WHEN 'FINISHED' THEN 1\n    WHEN 'BROKEN' THEN 2\n  END status\nFROM\n  telemetry\nWHERE\n  thing_name='$device'\nAND\n  ns='ComponentStatus'\nAND\n  ts / 1000 >= $__unixEpochFrom() AND ts / 1000 <= $__unixEpochTo() \nORDER BY time ASC;"
    }
   ]
  }
 ]
}