---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component injects additional information into the telemetry emitted by aws.greengrass.telemetry.NucleusEmitter and then publishes the modified telemetry to a new topic."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.Cli:
    VersionRequirement: ^2.0.0
    DependencyType: SOFT
  aws.greengrass.telemetry.NucleusEmitter:
    VersionRequirement: ^1.0.0
    DependencyType: SOFT
ComponentConfiguration:
  DefaultConfiguration:
    TelemetryPublishTopic: "injected/greengrass/telemetry"
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.offline.TelemetryInjector:pubsub:1:
          policyDescription: Allows access to publish and subscribe to any topic.
          operations:
            - "*"
          resources:
            - "*"
Manifests:
  - Platform:
      os: /darwin|linux/
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.offline.TelemetryInjector.zip"
        Unarchive: ZIP
    Lifecycle:
      Install: "pip install awsiotsdk"
      Run: "python3 -u {artifacts:decompressedPath}/com.offline.TelemetryInjector/inject.py 
                {configuration:/TelemetryPublishTopic}"
