---
RecipeFormatVersion: '2020-01-25'
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: 'A component that relays and publishes telemetry from Greengrass to Postgres.'
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
    aws.greengrass.telemetry.NucleusEmitter:
      VersionRequirement: ">=1.0.0"
      DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
    TelemetryTopic: injected/greengrass/telemetry
    PostgreSQLSecretArn: "arn:aws:secretsmanager:us-east-1:647314867318:secret:postgres/auth-88ezha"
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.offline.telemetry.PostgresPublisher:pubsub:1:
          policyDescription: Allows access to subscribe to local Greengrass telemetry.
          operations:
            - "*"
          resources:
            - "*"
      aws.greengrass.SecretManager:
        com.offline.telemetry.PostgresPublisher:secrets:1:
          operations:
            - "aws.greengrass#GetSecretValue"
          policyDescription: "Allows access to the secret containing PostgreSQL and Grafana credentials."
          resources:
            - "arn:aws:secretsmanager:us-east-1:647314867318:secret:postgres/auth-88ezha"
Manifests:
  - Platform:
      os: /darwin|linux/
    Lifecycle:
      Run:
        script: "pip install awsiotsdk psycopg2-binary && 
                python3 -u {artifacts:decompressedPath}/com.offline.telemetry.PostgresPublisher/publisher.py
                  --telemetry_topic {configuration:/TelemetryTopic}
                  --postgresql_secret_arn {configuration:/PostgreSQLSecretArn}"
    Artifacts:
    - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.offline.telemetry.PostgresPublisher.zip"
      Unarchive: ZIP
