---
RecipeFormatVersion: "2020-01-25"
ComponentName: "{COMPONENT_NAME}"
ComponentVersion: "{COMPONENT_VERSION}"
ComponentDescription: "This component will send an message to a configured SNS topic and run a local alarm script."
ComponentPublisher: "{COMPONENT_AUTHOR}"
ComponentDependencies:
  aws.greengrass.TokenExchangeService:
    VersionRequirement: "^2.0.0"
    DependencyType: HARD
ComponentConfiguration:
  DefaultConfiguration:
    TopicArn: "arn:aws:sns:region:account:topic"
    AlarmCommand: "echo test"
    accessControl:
      aws.greengrass.ipc.pubsub:
        com.offline.telemetry.PostgresPublisher:pubsub:1:
          policyDescription: Allows access to subscribe to local Greengrass telemetry.
          operations:
            - "*"
          resources:
            - "*"
Manifests:
  - Platform:
      os: all
    Lifecycle:
      Install: "pip install boto3"
      Run: "python3 -u {artifacts:decompressedPath}/com.offline.Alarm/alarm.py 
              --sns_topic '{configuration:/TopicArn}'
              --on_alarm_command '{configuration:/AlarmCommand}'"
    Artifacts:
      - URI: "s3://BUCKET_NAME/COMPONENT_NAME/COMPONENT_VERSION/com.offline.Alarm.zip"
        Unarchive: ZIP
        
